# Generated by Django 5.0.6 on 2024-07-15 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_promocion_habitacion_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='precio',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('SUITE', 'Suite')], default='SINGLE', max_length=10),
        ),
    ]
